
import "./globals.css";
import Footer from "./components/Footer"
export const metadata = {
  title: "voxez",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/parsaasadzadeh/voxez@master/style.css" />
      </head>
      <body
        className={` antialiased  bg-black min-h-full animated-bg`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
