
export const metadata = {
  title: "voxez-documents",
  description: "Generated by create next app",
};

import Documents from "./Documents";
const doc = () =>{

  return(
    <>
    <Documents/>
    </>
  )
}

export default doc;